### PR TITLE
Fetch credentials every 15 minutes and save them to file.

### LINKED ISSUE #90: Receive credentials from the server
*Subtask of WoTTsecurity/api#86*
*Requires #89*

Schedule periodic GET request to `/api/.../creds` every 15 minutes. Write the result to a file.

Credentials are in the form of `[{"name": ..., "key": ..., "value": ...}, ...]`. Agent should write `{key: value, ...}` to a file named `{name}.json` (grouping credentials by `name`).

### PR DESCRIPTION
**Pull request by a-martynovich**
Closes #90.

### CODE REVIEW

**Comment by vpetersson** [comment]
@a-martynovich I don't think this is a good implementation, and here's why. 

Let's imagine that you have two set of credentials for two different applications. Let's call them App0 and App1. 

App0 is not super sensitive. It's a 3rd party software and requires a requires an API key. The fleet owner is  using this same API key across the entire fleet of devices and the service as running as `weather-user`.

App1 on the other hand is very sensitive. It's a unique API key that is used for the device to report in data to the back-end. This service is running as the user 'foobar'.

To mitigate the above problem, we need to provide more granularity for permission such that App0 cannot read App1's credentials and vice versa. As such, all credentials cannot reside in the same file.

Instead of the above approach, I suggest that we move to JSON on disk and have each set of credentials being its own file. That way we can regulate access control for the use case above and regulate such that only the weather-user can access the weather-app and 'foobar' the sensitive API key.

Moreover, by using JSON, it's easier for 3rd party services to read in the file.

Yes, this is only true for services not running as root, but it's at least a first layer of defence.

(ping @rptrchv)

**Comment by a-martynovich** [comment]
@vpetersson I thought we were going to provide an API for this, so that only agent has access to creds store, and it checks who's requesting the creds before giving them away.

How do we differentiate between sets of credentials? As per WoTTsecurity/api#86 you said it's simply a fleet-local key-value store. And now we have these sets?

**Comment by vpetersson** [comment]
> @vpetersson I thought we were going to provide an API for this, so that only agent has access to creds store, and it checks who's requesting the creds before giving them away.

Honestly, I've been going back and forth on this. Right now I'm leaning towards writing them out to disk as we would get some basic permission security with minimal complexity.

> How do we differentiate between sets of credentials? As per [WoTTsecurity/api#86](https://github.com/WoTTsecurity/api/issues/86) you said it's simply a fleet-local key-value store. And now we have these sets?

Yes, you're absolutely right. I've been thinking about this for a fair amount of time and I think I simply forgot to update you guys on my thinking.

**Comment by vpetersson** [comment]
Closed in favor of #107.

**Pull request closed without merging**
