### PR TITLE
UDP ports blocking fix

### PR DESCRIPTION
**Pull request by rptrchv**
Update agent side in order to support ports blocking data format change in https://github.com/WoTTsecurity/api/issues/69

### CODE REVIEW

**Comment by a-martynovich** [comment]
@rptrchv So currently the agent can receive block request for TCP and UDP, but can only block TCP ports. Should I implement UDP blocking in this branch or is it already done somewhere else?

**Comment by rptrchv** [comment]
> @rptrchv So currently the agent can receive block request for TCP and UDP, but can only block TCP ports. Should I implement UDP blocking in this branch or is it already done somewhere else?

Fixed that in the new commit

**Comment by rptrchv** [comment]
Tested, works fine

**Comment by a-martynovich** [comment]
👍

**Comment by vpetersson** [comment]
s/:+1: /LGTM/g

**Pull request merged**
