### PR TITLE
Fix default password detection

### PR DESCRIPTION
**Pull request by a-martynovich**
Closes wottsecurity/api#232

### CODE REVIEW

**Comment by vpetersson** [comment]
@a-martynovich if we're going down this path, we should probably user pairs (i.e. pi:raspberry) because in other distros, it won't be the user 'pi'.

**Comment by a-martynovich** [comment]
@vpetersson I'll do that after I'm done with other urgent tasks if there still be time left.

**Comment by vpetersson** [comment]
@a-martynovich let's fix the credential pairs before merging this.

**Comment by a-martynovich** [comment]
@vpetersson What do you mean by that? And how does this affect credentials?

**Comment by vpetersson** [comment]
What i mean is that we should check against "pi:raspberry" (i.e a mapping) rather than just the password. In the future, we will have more (such as "root:password") for instance.

**Pull request merged**
